// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUcEZgJ6MoyaFaobrLwdHgBp6HObk_IAE',
    appId: '1:412314307824:web:376dc90a12d506a7b84635',
    messagingSenderId: '412314307824',
    projectId: 'medware-d05d6',
    authDomain: 'medware-d05d6.firebaseapp.com',
    storageBucket: 'medware-d05d6.appspot.com',
    measurementId: 'G-FX1FBH86FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BRxz6P1uQCDvnFkOQSFLhVqHy2SCbwY',
    appId: '1:412314307824:android:b432c35a6fad5b75b84635',
    messagingSenderId: '412314307824',
    projectId: 'medware-d05d6',
    storageBucket: 'medware-d05d6.appspot.com',
  );
}
